# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.3'
# Define services
services:
  # App backend service
  server:
    # Configuration for building the docker image for the backend service
    build:
      context: projectbackend # Use an image built from the specified dockerfile in the `app-server` directory.
      dockerfile: Dockerfile # Specify the Dockerfile path
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container (docker) to port 8080 on the host machine
    
    depends_on:
      - db # This service depends on mysql. Start that first.
      - zookeeper
      - kafka
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/opensky?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: palavrapasse
    networks: # Networks to join (Services on the same network can communicate with each other using their name and no need of address)
      kafka-net:
        ipv4_address: 172.0.0.3
  # Frontend Service
  client:
    build:
      context: projectfrontend # Use an image built from the specified dockerfile in the `app-client` directory.
      dockerfile: Dockerfile # Specify the Dockerfile path
    ports:
      - "3000:3000" # Map the exposed port 80 on the container to port 80 on the host machine
    
    depends_on:
      - server
    networks:
      kafka-net:
        ipv4_address: 172.0.0.4
        
  # Kafka Consumer Backend
  consumer:
    # Configuration for building the docker image for the backend service
    build:
      context: kafkaConsumer # Use an image built from the specified dockerfile in the `app-server` directory.
      dockerfile: Dockerfile # Specify the Dockerfile path
    ports:
      - "8081:8081" # Forward the exposed port 8080 on the container (docker) to port 8080 on the host machine
    depends_on:
      - server
    networks: # Networks to join (Services on the same network can communicate with each other using their name and no need of address)
      kafka-net:
        ipv4_address: 172.0.0.7
  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306"
    
    environment:
      MYSQL_DATABASE: opensky
      MYSQL_ROOT_PASSWORD: palavrapasse
    volumes: # volumes could help in case we lost stored data (it persist data in host machine in the db-data directory)
      - db-data:/var/lib/mysql
    networks:
      kafka-net:
        ipv4_address: 172.0.0.2

  zookeeper:
    image: 'wurstmeister/zookeeper'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      kafka-net:
        ipv4_address: 172.0.0.5
    ports:
      - '2181:2181'
    expose: 
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'wurstmeister/kafka'
    networks:
      kafka-net:
        ipv4_address: 172.0.0.6
    ports:
      - '9092:9092'
    expose:
      - '9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.0.0.6
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "openskyevents:1:1"
      KAFKA_CREATE_TOPICS: "opensky:1:1"
    depends_on:
      - zookeeper
  
# Define Volumes to be created
volumes:
  db-data:
# Define Networks to be created to facilitate communication between containers
networks:
  kafka-net:
    ipam:
      driver: default
      config: 
        - subnet: 172.0.0.0/24
