# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.3'
# Define services
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # App backend service
  server:
    # Configuration for building the docker image for the backend service
    build:
      context: projectbackend # Use an image built from the specified dockerfile in the `app-server` directory.
      dockerfile: Dockerfile # Specify the Dockerfile path
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container (docker) to port 8080 on the host machine
    
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/opensky?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: palavrapasse
    networks: # Networks to join (Services on the same network can communicate with each other using their name and no need of address)
      - backend
      - frontend
  # Frontend Service
  client:
    build:
      context: projectfrontend # Use an image built from the specified dockerfile in the `app-client` directory.
      dockerfile: Dockerfile # Specify the Dockerfile path
    ports:
      - "3000:3000" # Map the exposed port 80 on the container to port 80 on the host machine
    
    depends_on:
      - server
    networks:
      - frontend
  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306"
    
    environment:
      MYSQL_DATABASE: opensky
      MYSQL_ROOT_PASSWORD: palavrapasse
    volumes: # volumes could help in case we lost stored data (it persist data in host machine in the db-data directory)
      - db-data:/var/lib/mysql
    networks:
      - backend
# Define Volumes to be created
volumes:
  db-data:
# Define Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:
